### ISSUE TITLE
Importing Database Crashes App

### ISSUE THREAD

**Issue by JohnJohn9312** [popcorn-official/popcorn-desktop#132] opened 2016-04-02 00:21 UTC
Operating System Version:
OsX 10.11.3

Popcorn Time Version:
0.3.9-0

Download date:
Feb. 22, 2016

#### Expected Behavior
I exported my database in the settings so that when the app crashes or resets itself I could easily import the database to restore all of my bookmarks and watched items and settings. When I go to import the database, I expect to restart the app and then see my bookmarks reappear in the favorites view.
...

#### Actual Behavior
I am able to successfully import the database and PT tells me "Success, please restart PT", so I click restart. Then when PT opens back up, it gets stuck loading on the Int. Database. I then have to click the loading stuck, click here button, which resets my PT and then I loose all my favorites and such, causing me to need to import my database I had previously exported, but then it freezes on startup at Int. Database every time.
...

#### Steps to repoduce the behaviour

1. Go into setting and export your database
2. Then, I changed the code to make the movie posters show up in the favorites view from a post I found on here. PopcornTime worked normally.
3. I was watching something when the NWJS player quit unexpectedly, which made my PT restart and loose all of it's saved setting, favorites, etc.
4. Then, I went into setting and imported my saved database, and clicked restart PT when prompted. PopcornTime then froze on the startup screen when Int. Database was displayed.

**Comment by VitorVRS** [comment] 2016-04-22 01:58
Have you tried the latest build?
I couldn't reproduce this.

**Comment by JohnJohn9312** [comment] 2016-04-22 02:04
Well I tried the latest build like a few weeks to a month ago, but I'll try again. Thanks.

**Comment by Breaking1** [comment] 2016-04-22 09:30
Since the auto updater in the app isn't working/activated you need to re-download from the official site to get the latest version, the problem your talking about was present in some earlier builds but should be fixed now.

**Closed** 2016-10-20 17:21 UTC
