### ISSUE TITLE
Subtitles don't work when casting to SmartTV

### ISSUE THREAD

**Issue by CViniciusSDias** [popcorn-official/popcorn-desktop#1495] opened 2020-05-31 16:01 UTC
Operating System Version:
Linux Mint 19.3

Popcorn Time Version:
0.4.4-0

Download date:
05/31/2020

Download url (optional):
https://get.popcorntime.app/build/Popcorn-Time-0.4.4-linux64.zip

#### Expected Behaviour
When I try to watch a movie on my Smart TV, I would expect the subtitles to show, just how they do on PopcornTime player

#### Actual Behaviour
The subtitles aren't displayed on the SmartTV

#### Steps to reproduce the behaviou

1. Turn your SmartTV on
2. Open PopcornTime and choose a movie
3. Select the subtitles language
4. Select your TV as the player
5. Click "Watch Now"
6. Observe that the subtitles don't show up

#### Screenshot of error from developer console (optional)
![https://imgur.com/a/JzdaKDT](https://i.imgur.com/XaTGv7b.png)

**Comment by gramagrass** [comment] 2020-09-14 23:26
This is happening to me also. Any news about this issue?

**Comment by kiriles90** [comment] 2020-10-01 00:27
@Persei08 duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1244, close please

**Closed** 2020-10-01 05:29 UTC
